// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto1.Data;

#nullable disable

namespace Proyecto1.Migrations
{
    [DbContext(typeof(RedVialContext))]
    [Migration("20250509005729_AgregarReferenciasNodos")]
    partial class AgregarReferenciasNodos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nodo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstadoSemaforo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNodoEste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNodoNorte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNodoOeste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNodoSur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoPromedioCruce")
                        .HasColumnType("int");

                    b.Property<string>("TipoViaEste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoViaNorte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoViaOeste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoViaSur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehiculosEnEspera")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Nodos");
                });

            modelBuilder.Entity("Proyecto1.Models.ReporteRedVial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CuellosBotellaTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterseccionMasCongestionada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodosTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
